version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version
  pre_build:
    commands:
      - cd terraform
      - terraform init -reconfigure
      - terraform validate
  build:
    commands:
      - terraform plan -out=tfplan
  post_build:
    commands:
      - terraform apply -auto-approve tfplan
